### PR TITLE
Add read support for expiring passwords

### PR DESCRIPTION
**Pull request by elmir-b**
Being a keepmenu user I saw one missing feature - which is support for expiring passwords. I have this in multiple cases, and worst of all there are no (email) notifications when the password is expiring by the websites I'm using.

So, I wanted to make my life easier and as well contribute to anyone else who might need it, so I added the possibility to check the expiry times for passwords as well as a message on the root level when there are passwords that are about to expire or have expired.

This is read only support, so there is no possibility to edit the expiry times in keepmenu. With all of the timezone and datetime formatting "issues" I decided not to do it at this time. If there is need for it it can be added later, but I anyway use other tools for editing/adding and keepmenu only for filling the passwords where needed, so this solution suits my needs perfectly.

### CODE REVIEW

**Comment by elmir-b** [comment]
How it looks like:
main menu
image
view entry
image

**Comment by firecat53** [comment]
What do you think about the alternate UI in my `support_read_of_expiry_dates`
branch? Instead of adding a separate menu entry, it just prepends "EXPIRED" to
the path when the list of entries is displayed. My next thought is to move all
the EXPIRED entries to the top of the list to make them more visible.

I did this as an experiment to see if we could avoid adding yet another menu
entry, as the list of options keeps growing!

Thoughts?

**Comment by elmir-b** [comment]
> What do you think about the alternate UI in my `support_read_of_expiry_dates`
> branch? Instead of adding a separate menu entry, it just prepends "EXPIRED" to
> the path when the list of entries is displayed. My next thought is to move all
> the EXPIRED entries to the top of the list to make them more visible.
> 
> I did this as an experiment to see if we could avoid adding yet another menu
> entry, as the list of options keeps growing!
> 
> Thoughts?

so I only added it to the main menu because I would like to see that I have passwords expiring, I would very rarely scroll through all of them, and might not even use or see some at all before they expire. Moving the expiring ones to the top might solve the issue.

Also not sure if you noticed, but this menu item exists only when there are passwords expiring. So normally it wouldn't even be there, not sure if that makes a difference for you.

So to conclude, both approaches would work for me, I would maybe prefer the one with a menu item, but it is just personal preference. 

Did you consider reorganizing the menu and making an "Advanced" (or Manage or Settings or something) item on the top level, and then just putting "Kill daemon", "Open another database" and "Reload database" inside? These are useful options and definitely needed, I am just not sure they are needed on the top level (if cluttering is becoming a problem)

**Comment by firecat53** [comment]
Merged, thanks! I ended up going with your way, just making some minor edits and
cleanups. Appreciate the help!

**Comment by elmir-b** [comment]
no problem, happy to contribute as I use keepmenu every day

**Pull request closed without merging**
