### PR TITLE
add support for keeotp & keepass2 otp fields

### LINKED ISSUE #117: Some TOTP entries are not working
For some of my database entries there is no TOTP value generated. But KeepassXC can generate it and when I use keepmenu to "View/Type individual entries" and go to the entry, I can see two fields "TOTP Seed" and "TOTP Settings", but the "TOTP" field is empty.

### PR DESCRIPTION
**Pull request by bdeshi**
closes #117

TODO
- [x] support keeotp's `key=...` style otp field
- [x] support keepass2's totp fields
- [x] add tests

### CODE REVIEW

**Comment by bdeshi** [comment]
@firecat53 keepmenu currently supports only base32 encoded otp seeds, i'm doing the same here. support for additonal encodings may be better implemented in a different subsequent PR.
ditto for hotp support. keepmenu currently assumes all otps are of the totp type.

**Comment by firecat53** [comment]
Sorry about the delay!! Thanks for the work on this, looks good to me. Do you think there's value in adding documentation to what OTP formats are supported into `docs/usage.md`? If so, perhaps include some of the links to the documentation that you provided in #117? 

If you can rebase on top of the `totp` branch (I updated my email address recently) after any docs are updated, I'll go ahead and merge this.

Thanks again!

**Comment by bdeshi** [comment]
@firecat53 how does it look now?

**Comment by firecat53** [comment]
Awesome, thanks so much!

**Pull request merged**
