### PR TITLE
Add support for additional attributes

### PR DESCRIPTION
**Pull request by anguye21**
In KeepassXC users can add [Additional Attributes](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_additional_attributes) to an entry to store whatever information they want. This PR adds the ability to add, edit and access this data.

### CODE REVIEW

**Comment by firecat53** [comment]
Thanks! I'll hopefully get to this sometime this week. Looks like this would fix #43 as well.

**Comment by firecat53** [comment]
1. Can you please rebase onto the latest main. I pushed some changes over the past few days.
2. Currently you cannot view the value of the additional attributes from the 'View/Type Individual entries->entry' view without actually autotyping it. What I'd like to see instead is to add each attribute as an additional entry in the menu like:
    
        ....
        URL: None
        Notes: None
        Expiry date: None
        <Attribute 1 name>: value
        <Attribute 2 name>: value

That way you can see the attribute name and value immediately and then select it to type the value directly. I'd also like to see that philosophy applied to the edit menu as well. So the menu would read:

        ......
        Expiry date: None
        <Attribute 1 name>: value
        <Attribute 2 name>: value
        Add Attribute

Now select `<Attribute 1 name>: value` and see:

        <Attribute 1 name>
                value
                Delete Attribute

3. Make sure to account for hitting `Esc` in any menu to either back up one menu level or to back out completely (depending on location). The PR as written currently throws a `KeyError: ''` when hitting escape from the list of attributes. 
4. Please add one or more attributes to an entry in test.kdbx and ensure they are retrieved correctly. I haven't thought through what that test would look like yet, but we can chat about that later if nothing obvious comes to you, either!

Thanks so much for the time and effort! I think this is a useful addition to the tool.

**Comment by anguye21** [comment]
Everything you requested should be fixed now. I have an NVIDIA GPU so I can't test if autotype with ydotool and wtype works so if you could check if those work that would be fantastic.

**Comment by firecat53** [comment]
I think just a few more details and we should be done with this! Thanks for your patience and detailed work.

1. Bug: When adding a new attribute, when you hit `Esc` while entering the name, it should exit back to the edit menu for that item (check how editing username, for example, responds). Instead, it adds a blank item and continues on to ask for a value.
2. Change: When editing an attribute, I think it should present the same interface as when editing other items, specifically instead of:

        Attr 1: one
                  Edit
                  Delete

I think it should look (again, check how username is edited) like:
   
        Attr 1:
            one
            Delete

You should just be able to type in a new name right away, or select delete without the extra step of selecting Edit. Hopefully that makes sense.

3. Question: What would you think about changing the display of the attributes
   by removing the `"` marks from around the values (like the other items are
   currently) and removing the 'Attribute' label? So like:
   
        ....
        Notes: None
        Expiry date: None
        Attr 1: one
        Attr 2: two

I personally think it looks a little cleaner, and I think the user is already going to know that it's a non-standard field.

4. Lastly, we should update the README, man page, and possibly usage.md doc to reflect the new capability.

Again, I really appreciate your work on this! 

Scott

**Comment by firecat53** [comment]
I just pushed a commit that I think addresses your concern. Since we have the exact key and value, it's easy to match without needing the regex. Let me know if it looks ok!

**Comment by anguye21** [comment]
yeah, that seems to work. Thanks for the help

**Comment by firecat53** [comment]
After looking at KeepassXC again, I realized that the attribute values could be
multiple lines, just like the Notes. Latest commit addresses that for viewing
and editing. Can you please test it out for me before I merge this whole PR?

**Comment by anguye21** [comment]
Everything looks good!

**Pull request merged**
