### PR TITLE
Database specific autotype

### LINKED ISSUE #92: Implement database-specific autotype defaults
For my use case I use separate databases for passwords and TOTPs security reasons as [recommended](https://keepassxc.org/docs/#faq-security-totp) by KeepassXC. However, in keepmenu's current state, I cannot add autotype defaults to set the appropriate behaviour. 

In the meantime, I've been using this configuration option
```ini
autotype_default = {PASSWORD}{TOTP}{ENTER}
```
and modified [this](https://github.com/firecat53/keepmenu/blob/e301b32be79c69096b7824476f8be00845e32233/keepmenu#L1095) return statement so it doesn't crash when it cannot find the autotype token.
```diff
     except KeyError:
         steam = False
 
-    return totp(
-        query_string['secret'][0], int(query_string['period'][0]),
-        int(query_string['digits'][0]), 'sha1' if 'algorihm'
-        not in query_string else query_string['algorithm'][0].lower(), steam)
+    try:
+        return totp(
+            query_string['secret'][0], int(query_string['period'][0]),
+            int(query_string['digits'][0]), 'sha1' if 'algorihm'
+            not in query_string else query_string['algorithm'][0].lower(), steam)
+    except KeyError:
+        return
 
 
 def add_entry(kpo):
```

but this prevents me from using something like this
```ini
autotype_default_1= {USERNAME}{TAB}{PASSWORD}{ENTER}
autotype_default_2 = {TOTP}{ENTER}

### PR DESCRIPTION
**Pull request by anguye21**
closes #92

### CODE REVIEW

**Review by firecat53 — CHANGES_REQUESTED** [review]
1. Please update docstring for `type_entry`
2. Please ensure tests pass and add tests as necessary for the new
   functionality.
   
Thanks!

**Review by firecat53 — CHANGES_REQUESTED** [review]
Found an error that shows up when using a keyfile. This diff will fix, near as I
can tell:

    diff --git a/keepmenu b/keepmenu
    index 1e3e327..bbea6a6 100755
    --- a/keepmenu
    +++ b/keepmenu
    @@ -343,8 +343,8 @@ def get_database(open_databases=[]):
                 return dbr
         if not dbs[0][-2]:
             db_l = list(dbs[0])
    -        db_l[-1] = get_passphrase()
    -        if not db_l[-1]:
    +        db_l[-2] = get_passphrase()
    +        if not db_l[-2]:
                 return (None, None, None, None)
             dbs[0] = db_l
         return tuple(dbs[0])

**Comment by anguye21** [comment]
Can you tell me how to reproduce the issue you saw with the keyfile? I don't see any problems when I try with a keyfile.

**Review by firecat53 — CHANGES_REQUESTED** [review]
When launching keepmenu like: `keepmenu -a '{TOTP}{ENTER}'`, if an entry is
selected (typed) that doesn't have a TOTP secret assigned, I get the following
error:

		Traceback (most recent call last):
		  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
			self.run()
		  File "/home/firecat53/docs/family/scott/src/projects/keepmenu/./keepmenu", line 1483, in run
			self.dmenu_run()
		  File "/home/firecat53/docs/family/scott/src/projects/keepmenu/./keepmenu", line 1561, in dmenu_run
			type_entry(entry, self.database[3])
		  File "/home/firecat53/docs/family/scott/src/projects/keepmenu/./keepmenu", line 518, in type_entry
			type_entry_xdotool(entry, tokens)
		  File "/home/firecat53/docs/family/scott/src/projects/keepmenu/./keepmenu", line 751, in type_entry_xdotool
			to_type = PLACEHOLDER_AUTOTYPE_TOKENS[token](entry)
		  File "/home/firecat53/docs/family/scott/src/projects/keepmenu/./keepmenu", line 531, in <lambda>
			"{TOTP}"    : lambda e: gen_otp(e.get_custom_property("otp")),
		  File "/home/firecat53/docs/family/scott/src/projects/keepmenu/./keepmenu", line 1109, in gen_otp
			query_string['secret'][0], int(query_string['period'][0]),
		KeyError: 'secret'

If the `-a` isn't passed, and an entry with `TOTP: None` is selected, the words
"TOTP: None" is 'opened' in a web browser. Probably should be fixed so nothing
happens, but not necessarily as part of this PR.

**Comment by firecat53** [comment]
I have a keepass database assigned in config.ini with a keyfile that also has a
password. When opening the database with keepmenu, I type the password and then
it pops up an empty "Error:" window and exits. I think this because line 347
should read `db_l[-2] = get_passphrase()`, as the password is now the 3rd of 4
fields in the db tuple.

**Pull request merged**
