### PR TITLE
Generate TOTP codes like KeePassXC

### PR DESCRIPTION
**Pull request by anguye21**
Adds feature that was requested in #86

### CODE REVIEW

**Review by firecat53 — CHANGES_REQUESTED** [review]
Is the print statement `print(otp_url)` just for debugging? It should probably
be removed so it doesn't print the secret to stdout when the TOTP is edited.

**Review by firecat53 — CHANGES_REQUESTED** [review]
Couple of more housekeeping items:

1. Please add docstrings to your methods similar to existing docstrings
2. I think the editing section for totp is long enough to warrant a separate
   method similar to edit_notes.
3. Remove line `# Put code here` (pretty sure that was a placeholder for you?)
4. I'm trying to conform (mostly) to pylint defaults, so please change the
   variable `o` in gen_otp to a 3 char variable. I fully recognize I've got some
   work to do in this department :D

Thanks very much!

**Comment by anguye21** [comment]
Do you have any better ideas for editing the TOTP? I do think that the way I have it currently is a bit clunky, but I can't think of a better way for someone to set it up, since there is a very constrained amount of choices. I guess entering the secret key in a text editor would be nice, but for the other options, I just can't think of something else.

**Comment by firecat53** [comment]
Editing entries with keepmenu is never going to be as easy as with a gui or tui. I think it's just gonna be clunky! Couple of other suggestions I've found:

1. When editing the secret key have the existing value as the default value (just like I do with the password entry). That way people can see the key value if necessary.
2. Add some basic error checking with the key entry. I entered a random secret key and then got a `binascii.Error: Non-base32 digit found` when trying to type the totp.
3. When adding a new entry, the TOTP value should read 'None'. Right now there seems to be a default value that appears as '****'.

Thanks! I think we're getting close here!

**Comment by firecat53** [comment]
Thanks again for this! I made a few cosmetic changes and minor bug fixes before
merging your PR. I'm going to take this PR and use it as a basis for adding TOTP
support to my bitwarden-menu project as well :)

**Comment by firecat53** [comment]
I just realized we should probably add some unit tests for the TOTP functions.
Opened a new issue to track.

**Pull request closed without merging**
