### PR TITLE
Add support for wtype

### PR DESCRIPTION
**Pull request by bwidawsk**
[wtype](https://github.com/atx/wtype) is an alternative to ydotool which doesn't require some of the hoops you have to jump through to support ydotool.

### CODE REVIEW

**Comment by bwidawsk** [comment]
With this, it might be wise to add a delay option to config.ini. I've noticed wtype is really fast and in certain situations, data isn't entered properly.

**Comment by firecat53** [comment]
I was actually just working last week on adding support for the `{DELAY=x}`
token to slow down typing speed for a given entry :)

**Comment by bwidawsk** [comment]
I'm seeing some oddness. I'll dig into it a bit. Just FYI.

**Comment by firecat53** [comment]
Merged, thank you!

**Pull request closed without merging**
