### PR TITLE
Add Feature: Check Leaked (Pwned) Passwords

### PR DESCRIPTION
**Pull request by BrachystochroneSD**
**Add an option to check if some of yours passwords has been leaked by using the the api of "Have I been Pwned?" website.**
The idea came from the [last video of Computerphile.](https://www.youtube.com/watch?v=hhUb5iknVJs)

The added option simply check the passwords of all entries and create a list of the leaked ones. You can then edit them one by one.

**How this method check if the password has been leaked?** 
It works by sending only the first 5 digits of the hashed (sha1) password, the code just check if the full hash is in the list of hashes that starts with the same 5 digits from the get request. Your password stay safe in your computer.

I first thought that it wasn't a relevant feature for someone who generate each of its passwords but leaks can happen in the future and the database of the website seems to be updated quite often. It can be helpful, who knows.

**Main issues:**
Since it's a get request, it can take some time to check all passwords (~5 sec for ~100 entries in my shitty computer). 
The feature need internet connection.

More infos: 
[Api Doc](https://haveibeenpwned.com/API/v2#PwnedPasswords)
[Wiki page of the website](https://en.wikipedia.org/wiki/Have_I_Been_Pwned%3F)

### CODE REVIEW

**Comment by firecat53** [comment]
Good idea but what would you think about adding it as a separate script that could be kept alongside the docs and then referenced in the README? It seems like something that should be more a utility than an integrated feature, especially for something relatively minimal like keepmenu.

Thoughts?

**Comment by BrachystochroneSD** [comment]
It's indeed a better idea to keep them separated. Since it's not something to check every day.

**Comment by firecat53** [comment]
Just checking if you are planning on submitting the standalone script as a separate pull request? Thanks!

**Comment by BrachystochroneSD** [comment]
Yes I am! If you're still ok with that.

I just have some other project right now, so maybe it will take a moment.

Scott Hansen writes:

**Comment by firecat53** [comment]
No worries, thanks!

**Comment by BrachystochroneSD** [comment]
Oh! Sorry, I didn't know that commits on this branch was automatically
linked to this pull request (I'm relatively new to the github
workflow. And specially with the pull request mecanism). I add this
feature just as a test, I didn't have in mind to make it "public".

But if you like the idea, I will add the check as you propose. I find the
utilisation of notify-send less "intrusive" that the dmenu
prompt (which "freeze" the screen until you press "return"), with the
cost of adding a new dependency of course. I don't know if it's better
in term of efficiency to use subprocess and notify-send/dunstify or use
the [notify2](https://pypi.python.org/pypi/notify2) python library.

I didn't even work on the standalone version of the pwned password
check. Sorry!

Scott Hansen writes:

> firecat53 requested changes on this pull request.
>
> This is a good idea, but how about adding a check for the existence of notify-send first and fall back to providing a dmenu notifcation if not. I'm guessing not everyone using this tool necessarily has desktop notifications enabled. Thanks!

**Comment by firecat53** [comment]
You might actually open a different PR with this request and rollback the changes you made on this branch just to keep it clean. Sorry, I should've mentioned that earlier :smiley:

**Comment by firecat53** [comment]
I still like the idea of this PR. What I'd like to see ideally (although happy to discuss options!!) is:

1. Separate script for the actual password checker. 
2. Makefile installing keepmenu and dependencies that uses `pip install --user` and installs the password check script to ~/.local/bin.

**Comment by BrachystochroneSD** [comment]
Still messed up with the branch. The makefile was for an other project. I forgot this PR (again), sorry. I've more free time now to finish that PR.

**Pull request closed without merging**
