### PR TITLE
Resolve KeePass references to values on autotype

### PR DESCRIPTION
**Pull request by elmir-b**
This PR resolves the issue of KeePass references being handled as values which instead of resolving the password (or other properties) value from KeePass DB and inserting where needed actually inserts the reference string - something like {REF:P........}

I am not a Python dev, so if there is a better way or place to do what I did here please let me know

Fixes firecat53/keepmenu#75

### CODE REVIEW

**Comment by firecat53** [comment]
Just started to check this out. Would you be willing to update the README and man page to reflect the new capabilities and add those to the PR? Thanks!

**Comment by elmir-b** [comment]
> Just started to check this out. Would you be willing to update the README and man page to reflect the new capabilities and add those to the PR? Thanks!

yup, already done, as mentioned in the readme and man page, I only added the capabilities for reading as I feel that adding the linking or editing capabilities would require more effort and not sure how much sense it makes as not even some tools like KeePassXC does not support adding/editing of references and only support the reading/auto-type

**Comment by firecat53** [comment]
Awesome! One more request (sorry I forgot to ask earlier): can you please add an example or two to the test database and add a test to check the functionality?

**Comment by elmir-b** [comment]
> Awesome! One more request (sorry I forgot to ask earlier): can you please add an example or two to the test database and add a test to check the functionality?

Done, I added an example and a small unit test that makes sure the value resolving function works

**Comment by firecat53** [comment]
Thanks!

**Comment by firecat53** [comment]
Well, I have to apologize. I didn't go through and check this as well as I should have and I ended up rewriting the whole thing. The way you had it written was actually overwriting the reference codes for that entry with the actual values in the database every time the database saved.

Anyway, I've got it all working correctly now including being able to edit the references. I just have to rewrite the tests and push it. I'll let you know when I do that so you can test it out for me if you have an existing database with reference values in it.

**Comment by firecat53** [comment]
Ok, I pushed the reworked reference support to the develop branch. If you could test it out and make sure it works as you would expect, I'd appreciate it!

**Comment by elmir-b** [comment]
@firecat53 I actually never saved the db through keepmenu. However it is a bit confusing having in mind python passes arguments by value, so I am not quite sure how that happens in the end.

anyway I checked the develop version:
One problem I see is that you can only call deref if the entry actually exists. I am also not sure what will deref return when called on entry that is not a reference.

right now I get this when I start the keepass:
`Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/elmir/projects/keepmenu/keepmenu", line 1298, in run
    self.dmenu_run()
  File "/home/elmir/projects/keepmenu/keepmenu", line 1362, in dmenu_run
    sel = view_all_entries(list(options), filtered_entries)
  File "/home/elmir/projects/keepmenu/keepmenu", line 899, in view_all_entries
    kp_entries_b = str("\n").join([kp_entry_pattern.format(j,
  File "/home/elmir/projects/keepmenu/keepmenu", line 900, in <listcomp>
    os.path.join("/".join(i.path[:-1]), i.deref('title')),
  File "/usr/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'`

**Comment by firecat53** [comment]
Found and fixed a bug, thanks! If the title was empty it threw that error. Give the develop branch another try.

**Comment by elmir-b** [comment]
Just tried it, now it looks a bit weird:
image

it seems to add a lot of backslashes

**Comment by firecat53** [comment]
Is that only for the dreferenced entry or for all entries?

**Comment by elmir-b** [comment]
yup, now it seems to work just fine. 

thanks!

**Pull request merged**
