### PR TITLE
Hide protected custom properties

### PR DESCRIPTION
**Pull request by vaygr**
Right now only multi-line custom properties are not explicitly displayed when you pull up an entry.

This change hides "protected" properties. In a way it mimics what the <kbd>Reveal</kbd> button does in KeePassXC.

This depends on the latest addition in pykeepass @ https://github.com/libkeepass/pykeepass/pull/322, so it shouldn't be merged/released until the next release of pykeepass.

Also keep in mind that protected attributes [are NOOP in pykeepass](https://github.com/libkeepass/pykeepass/pull/186) as all entries get decrypted at once on unlocking the database [contrary to the RFC](https://github.com/keepassxreboot/keepassxc-specs/blob/master/kdbx-xml/rfc.md#protected-elements).

### CODE REVIEW

**Comment by firecat53** [comment]
I'll take a look when they tag the next version, which should contain that  PR. If you don't hear from me within a week or so after that, ping me!

**Comment by firecat53** [comment]
Looks like pykeepass still hasn't tagged a new version with the fix needed for
this PR. Just checking in.

**Comment by vaygr** [comment]
They finally did: https://github.com/libkeepass/pykeepass/tags

**Comment by vaygr** [comment]
@firecat53 this is probably good to merge given 2 recent releases by upstream.

**Comment by vaygr** [comment]
@firecat53 great point. Fixed in the last commit.

**Pull request merged**
